import type { Product, Category, User } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Electronics",
    slug: "electronics",
    description: "Latest technology and gadgets",
    image: "/modern-electronics-category.png",
    subcategories: [
      { id: "1-1", name: "Smartphones", slug: "smartphones", description: "Latest mobile devices" },
      { id: "1-2", name: "Laptops", slug: "laptops", description: "Powerful computing devices" },
      { id: "1-3", name: "Headphones", slug: "headphones", description: "Audio equipment" },
      { id: "1-4", name: "Smart Home", slug: "smart-home", description: "Connected home devices" },
    ],
  },
  {
    id: "2",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing and accessories",
    image: "/fashion-clothing-category.png",
    subcategories: [
      { id: "2-1", name: "Men's Clothing", slug: "mens-clothing", description: "Stylish men's wear" },
      { id: "2-2", name: "Women's Clothing", slug: "womens-clothing", description: "Fashionable women's wear" },
      { id: "2-3", name: "Shoes", slug: "shoes", description: "Footwear for all occasions" },
      { id: "2-4", name: "Accessories", slug: "accessories", description: "Fashion accessories" },
    ],
  },
  {
    id: "3",
    name: "Home & Garden",
    slug: "home-garden",
    description: "Everything for your home and garden",
    image: "/home-garden-category.png",
    subcategories: [
      { id: "3-1", name: "Furniture", slug: "furniture", description: "Home furniture" },
      { id: "3-2", name: "Decor", slug: "decor", description: "Home decoration items" },
      { id: "3-3", name: "Kitchen", slug: "kitchen", description: "Kitchen appliances and tools" },
      { id: "3-4", name: "Garden", slug: "garden", description: "Gardening supplies" },
    ],
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    description: "The most advanced iPhone ever with titanium design, A17 Pro chip, and professional camera system.",
    price: 1199,
    originalPrice: 1299,
    category: "Electronics",
    subcategory: "Smartphones",
    images: ["/iphone-15-pro-max-front.png", "/iphone-15-pro-max-back.png", "/iphone-15-pro-max-side.png"],
    rating: 4.8,
    reviewCount: 2847,
    inStock: true,
    stockCount: 156,
    tags: ["bestseller", "premium", "new"],
    features: [
      "A17 Pro chip with 6-core GPU",
      "Pro camera system with 5x Telephoto",
      "Titanium design",
      "Action Button",
      "USB-C connectivity",
    ],
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Storage: "256GB",
      Camera: "48MP Main, 12MP Ultra Wide, 12MP Telephoto",
      Battery: "Up to 29 hours video playback",
      Weight: "221 grams",
    },
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    name: 'MacBook Pro 16"',
    description: "Supercharged by M3 Pro and M3 Max chips. Built for all the ways you work.",
    price: 2499,
    category: "Electronics",
    subcategory: "Laptops",
    images: ["/macbook-pro-16-inch-open.png", "/macbook-pro-16-inch-closed.png", "/macbook-pro-16-ports.png"],
    rating: 4.9,
    reviewCount: 1523,
    inStock: true,
    stockCount: 89,
    tags: ["professional", "premium"],
    features: [
      "M3 Pro or M3 Max chip",
      "16.2-inch Liquid Retina XDR display",
      "Up to 128GB unified memory",
      "Up to 8TB SSD storage",
      "22-hour battery life",
    ],
    specifications: {
      Processor: "Apple M3 Pro 12-core CPU",
      Memory: "18GB unified memory",
      Storage: "512GB SSD",
      Display: "16.2-inch Liquid Retina XDR",
      Weight: "2.16 kg",
    },
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "3",
    name: "AirPods Pro (2nd Gen)",
    description: "Adaptive Audio. Personalized Spatial Audio. Next-level Active Noise Cancellation.",
    price: 249,
    originalPrice: 279,
    category: "Electronics",
    subcategory: "Headphones",
    images: ["/placeholder-43htf.png", "/placeholder-9vmn4.png", "/airpods-pro-2-features.png"],
    rating: 4.7,
    reviewCount: 3421,
    inStock: true,
    stockCount: 234,
    tags: ["bestseller", "wireless"],
    features: [
      "Adaptive Audio",
      "Active Noise Cancellation",
      "Transparency mode",
      "Personalized Spatial Audio",
      "Up to 6 hours listening time",
    ],
    specifications: {
      Chip: "H2 chip",
      "Battery Life": "Up to 6 hours (ANC on)",
      "Case Battery": "Up to 30 hours total",
      Connectivity: "Bluetooth 5.3",
      "Water Resistance": "IPX4",
    },
    createdAt: "2024-01-08T10:00:00Z",
  },
  {
    id: "4",
    name: "Premium Cotton T-Shirt",
    description: "Soft, comfortable, and stylish cotton t-shirt perfect for everyday wear.",
    price: 29,
    originalPrice: 39,
    category: "Fashion",
    subcategory: "Men's Clothing",
    images: ["/premium-cotton-t-shirt-front.png", "/premium-cotton-t-shirt-back.png", "/premium-cotton-t-shirt-detail.png"],
    rating: 4.5,
    reviewCount: 892,
    inStock: true,
    stockCount: 456,
    tags: ["comfortable", "everyday"],
    features: [
      "100% organic cotton",
      "Pre-shrunk fabric",
      "Reinforced seams",
      "Available in multiple colors",
      "Machine washable",
    ],
    specifications: {
      Material: "100% Organic Cotton",
      Fit: "Regular fit",
      Care: "Machine wash cold",
      Origin: "Made in USA",
      Sizes: "XS to XXL available",
    },
    createdAt: "2024-01-05T10:00:00Z",
  },
]

export const mockUser: User = {
  id: "1",
  email: "john.doe@example.com",
  name: "John Doe",
  avatar: "/diverse-user-avatars.png",
  role: "customer",
  addresses: [
    {
      id: "1",
      name: "Home",
      street: "123 Main St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "USA",
      isDefault: true,
    },
  ],
  createdAt: "2024-01-01T10:00:00Z",
}
